import React from "react";

function Aikido() {
    return(
        <div className="content">
            <div className="content_title">
                <h1>JAPONSKÁ BOJOVÁ UMĚNÍ</h1>
            </div>
            <div className="content_content">
                <p>Japonská bojová umění byla vytvořena ve feudálním Japonsku jako prostředek boje o moc i jako prostředek individuální sebeobrany. Původně sloužila téměř výhradně k zabití nepřítele. V této podobě se i dnes uplatňují například při výcviku ozbrojených složek. Tato skupina bojových umění se japonsky nazývá budžucu (bu - válka, boj; džucu - umění, dovednost). Do této skupiny patří například původní japonský šerm a válečná lukostřelba. Hlavně počátkem 20. století došlo k přeměně budžucu v budó (dó - cesta; budó - cesta boje) a vzniku disciplín jako judó, karatedó, kendó, iaidó a dalších.</p>
                <p>V budó již není cílem zabití protivníka, ale především dokonalé poznání sebe sama a neustálé sebezdokonalování. Technika zde není cílem, ale prostředkem k dosažení sebepoznání. Cílem je dosažení naprosté harmonie tělesné i duševní stránky člověka. V budó se odráží hloubka kultury Dálného východu. Stejně jako při provozování kaligrafie, čajového obřadu nebo ikebany je v něm nadevše důležité soustředění na prováděnou činnost, spojené s estetikou lidského pohybu, a správné dýchání, o němž se říká, že spojuje tělo a duši.</p>
                <h1>Co je Aikido?</h1>
                <p>Aikido patří mezi nejmladší japonská bojová umění, neboť jej o sensei - velký mistr Morihei Uešiba (1883-1969) vytvořil až v roce 1925. Za zdroj mu posloužilo původní bojové umění aikidžicu s kořeny v 9. století, kendžucu (umění meče), džódžucu (umění krátké tyče) a džúdžucu (jemné umění). Ústřední ideou aikido je užití koordinované síly ki (vnitřní energie, duše) v harmonii či souladu (ai) s požadavky a okolnostmi boje.</p>
                <p>Aikido má velmi elegantní techniku, která je zcela založena na využití síly a reakcí protivníka. Principy techniky spočívají značnou měrou na technikách užití meče. Hlavní roli hraje koordinace s akcí protivníka. Aikido je relativně nenáročné na svalovou sílu, proto je vhodné nejen pro muže ale i pro ženy, děti a starší adepty. To v praxi dokazují lidé, kteří cvičí v našem dojo.</p>
                <p>Hlavní cíl aikidó lze přiblížit následujícím citátem: "Vybojovat tisíce bitev a tisíckrát zvítězit - to ještě není nejvyšší metou válečníka. Avšak podrobit si nepřítele bez boje, toť v pravdě vrchol umění." Sun - c'</p>
                <h1>Historie Aikido</h1>
                <p>Po smrti zakladatele, Moriheie Uesiby, pokračoval v rodinné tradici jeho syn Kišomaru Uešiba, který se zasloužil o počátky šíření aikida mimo Japonsko. V současné době udržuje rodinnou tradici vnuk zakladatele Moriteru Uešiba. Linie či styl reprezentovaný do současnosti rodinou Uešiba je označován jako aikikai, přímí žáci zakladatele (ó-sensei) ovšem někdy zakládají vlastní styly a školy. Centrálním dódžó v rámci linie aikikai je Hombu dojo v Tokiu, ve kterém vyučují členové rodiny Uešiba. První evropskou zemí odkud se aikido začalo dále šířit po starém kontinentu byla Francie. V počátcích většinou aikidistické oddíly vznikaly při judistických oddílech. První generace evropských aikidistů z 60. a 70. let měla většinou za sebou judistickou či karatistickou minulost. Mnozí vrcholoví judisté a karatisté se po skončení své sportovní kariéry věnují aikidu, jako blízké nesoutěžní formě bojového umění, které je založeno na podobných principech a při tom nevyžaduje příliš velké svalové vypětí.</p>
                <h2>Historie Aikido v České republice a Česká Asociace Aikido</h2>
                <p>Koncem 70. let začala aikido cvičit skupinka nadšenců na FTVS UK (I.Fojtík) a v džudistickém oddílu TJ Spoje pod vedením legendárního propagátora bojových umění pana Vladimíra "Kazika" Lorenze, dnes držitele 7. danu džúdó. Zásadní význam pro rozvoj aikido u nás měla ukázka pana G. Veneriho z Itálie (6.dan Aikikai, tehdy i předseda IAF a EAF) v roce 1986. Aikidó se pak po několik dalších let rozvíjelo během víkendových stáží pana G.Veneriho a dalších italských učitelů pořádaných oddílem Na Balkáně v Praze 3. Na tyto stáže se sjížděli zájemci z celých Čech i ze Slovenska.</p>
                <p>Koncem 80. let byly skládány první zkoušky na technické stupně v aikidó v Čechách (4.-6.kyú). První organizace aikido u nás Československá Aikikai byla založena 7. ledna 1990 ve snaze organizačně podchytit zvýšený zájem o aikido a využít možností souvisejících s celospolečenským uvolněním.</p>
                <p>V lednu 1991 byla založena Československá federace aikido (ČSFAI, později změněná na ČFAI). Bohužel mezinárodní pozice a politika vedení vedla k izolaci organizací ve vztahu k okolním zemím a také k Japonsku. V tomto období byly organizovány stáže mnoha zahraničních učitelů, zejména v dojo Aikido Kenkyukai Praha na TJ Spoje a čeští aikidisté se také častěji účastnili stáží v zahraničí. Snaha o udržení mezinárodních kontaktů a hlavně snaha o napojení na mezinárodní organizace aikido - linie Aikikai vedla k rozpadu organizace.</p>
                <p>V důsledku aktivit několika oddílů na mezinárodním poli vznikla koncem roku 1993 Česká asociace aikido (Aikikai of Czech Republic), která byla 8. dubna 1994 uznána zastřešující světovou organizací Hombu Dojo Tokyo. Technickým ředitelem ČAA se stal japonský šihan Masatomi Ikeda (7.dan Aikikai, Švýcarsko). V roce 1994 byla ČAA přijata do Evropské federace aikido (EAF). V roce 1996 pak do Mezinárodní federace aikido (IAF).</p>
                <p>V průběhu roku 2002 šihan Masatomi Ikeda nečekaně a vážně onemocněl. K lítosti všech svých studentů a organizací, pro které pracoval a rozvíjel aikido i svůj didaktický systém, byl k 1. lednu 2003 nucen ze zdravotních důvodů odstoupit ze všech funkcí a povinností, které vykonával z pověření Hombu Dojo pro národní organizace aikido v České republice (ČAA) i v dalších evropských zemích, z nichž mimo další jmenujme Švýcarsko, kde dlouhá léta žil (ACSA) a Slovenskou republiku (SAA). Většina těchto organizací pokračuje a rozvíjí aikido za změněných organizačních podmínek, ale stále ve smyslu senseiova odkazu.</p>
                <p>ČAA ustanovila šihana M.Ikedu do čestné funkce Technického ředitele ČAA a nová osoba ve funkci TŘ nebude ustanovena. Práci a příslušné kompetence v technické oblasti aikido převzala Technická komise ČAA, kterou řídí Daniel Vetter (Švýcarsko, dlouholetý žák a asistent M.Ikedy) a česká Zkušební komise na stupně dan Aikikai.</p>
                <p>K podzimu roku 2009 organizace ČAA úspěšně rozvíjí svou činnost a šíří aikidó v 40 oddílech po celé republice. Členská základna ČAA se již několik let ročně pohybuje okolo 700-800 členů, včetně skupiny okolo 80 členů ze tří polských klubů z Gdaňska. Roční členské poplatky s právem na zkoušky v rámci ČAA stanovuje každoročně Valná hromada ČAA.</p>
                <p>Organizaci ČAA jako členskou zemi IAF zastupoval její president Miroslav Kodym již na ctyřech kongresech této organizace, které probíhají v pravidelném čtyrletém cyklu v Japonsku. V roce 1998 organizovala ČAA v Praze dva kongresy EAF spojené se stážemi vedenými japonskými učiteli – šihan M. Ikeda (Švýcarsko), šihan Y. Kitaura (Španělsko), šihan M. Kanetsuka (Anglie). Při příležitosti oslavy 10. výročí ČAA proběhla v Praze stáž vedená dalšími japonskými sensei, kteří působí v Evropě – šihan H. Hosokawa (Itálie), šihan K. Asai (Německo), a koncem roku 2005 další víkendová stáž – šihan Y. Fujimoto (Itálie). Od roku 2007 pravidelně jednou ročně probíhají víkendové stáže ČAA pod vedením dvou z jmenovaných šihanů (K. Asai a Y. Fujimoto).</p>
                <p>Již od svých začátků organizuje ČAA v Praze v průběhu každého roku několik víkendových Stáží zahraničních učitelů ČAA pod vedením zahraničních učitelů (6. dan Aikikai ze Švýcarska) a v dalších městech ČR několik víkendových Národních stáží ČAA pod vedením D. Vettera a ročně přes deset víkendových Regionálních stáží ČAA (RS ČAA) pod vedením českých učitelů ze skupiny Šidóšakai ČAA (původně od 2. danu Aikikai, dnes od 3. danu Aikikai).</p>
                <p>Nejdůležitější akce ve struktuře ČAA probíhaly pod vedením šihana Masatomi Ikedy dvakrát ročně až do konce roku 2001 v Českých Budějovicích jako týdenní Letní škola ČAA a v Praze jako víkendová Zimní škola ČAA. Od roku 2002 pokračuje tradice obou těchto akcí s pravidelnou účastí kolem 150 lidí pod vedením současného ředitele TK ČAA senseie Daniela Vettera (6. dan Aikikai). Při ZŠ ČAA s ním od roku 2003 na výuce spolupracuje sensei Michele Quaranta (6. dan Aikikai v roce 2007) a při LŠ ČAA od roku 2005 sensei M. Kodym (5. dan Aikikai v roce 2007).</p>
            </div>
        </div>
    );
};

export default Aikido;