import React from "react";

const Historie = () => (
  <div className="content">
    <div className="content_title">
        <h1>AIKIDO NA PROSEKU (OD ROKU 1998)</h1>
    </div>
    <div className="content_content">
      <h3>AIKIDO NA PROSEKU 1998-2006</h3>
      <p>Je ode mne asi poněkud troufalé psát historii aikidistických aktivit, na kterých jsem se podílel jen skromnou částí, a proto se předem omlouvám všem, kteří snad z mé paměti vypadli. Spoluráce s Domem dětí a mládeže (dále jen DDM) na Proseku a pokusy zavést, zde pravidelnou výuku cesty harmonie sahají někdy do poloviny let devadesátých, ale o tom skutečně nejsem schopen něco napsat, protože nepatřím k pamětníkům a zřejmě pouze výkazy DDM z těchto let vydají svědectví o tom, kdo se pokoušel aikido šířit na proseckém sídlišti a kolik dětí bylo zlákáno sportovní aktivitou tohoto druhu.</p>
      <p>Já osobně jsem přišel do kontaktu s výukou aikido na Proseku někdy v průběhu roku 1998, jako za mnoho jiných věcí, které mají vazbu na šíření aikida v ČR, odpovědnost v tomto případě padá na hlavu pana Mirka Kodyma, který mě požádal, zda bych nevypomohl s výukou dětí na Proseku panu Danielovi Déme. Co bylo motivací pana Kodyma k tomuto kroku, nevím, snad se mu zdálo, že kombinace studenta teologie a historika-knihovníka bude tou správnou volbou. Osobně mám dojem, že opak byl pravdou, děti nám spíše přerůstaly přes hlavu a já si opět potvrdil, že spíše než pedagogika je mým charakterovým vlastnostem bližší andragogika. Rok jsem učil spolu s Danielem, ale nadějný teolog následně odejel rozšiřovat své znalosti středověké filozofie na univerzitu do hrdého Albionu a já zůstal sám. Ještě rok jsem vydržel, ale potom jsem podlehl pocitu zmaru a pochybnostem o smysluplnosti svého konání, každý půlrok nové děti a nové maminky s představou, že kroužek aikida je především pokračování školní družiny a zajistí spolehlivou ochranu jejich ratolestí před nástrahami pražského sídliště. Se školním rokem 2000 jsem definitivně podlehl náporům skepse a spolupráci s DDM ukončil. Skončeme s prehistorií a ponořme se do běhu času, který je nedávnou historií.</p>
      
      <h3>Tvrdé začátky</h3>
      <p>V průběhu roku 2002 jsem byl opět osloven panem Kodymem s tím, že vedení DDM nemůže nikoho sehnat na vedení kroužku aikida a že mají o pokračování této aktivity eminentní zájem a budou se snažit vyjít všem našim požadavkům maximálně vstříc. Panu Kodymovi jsem sdělil, že dle mého mínění nelze provozovat dětský oddíl bez klubu dospělých a je také nutné zajistit více jak jednoho učitele. Za sebe jsem sdělil, že sice stále pracuji poblíž, ale o vedení a řízení samostatného dojo zájem nemám a výuka dětí není zrovna mou silnou stránkou. Nevím, jak budou vzpomínat na tuto dobu Kuře a Smejki, ale nakonec se podařilo panu Kodymovi přemluvit partnerskou dvojici Legnerová-Smejkal. Slečna Legnerová byla čerstvou držitelkou prvního danu a tedy osobou dostatečně reprezentativní a pan Smejkal je dostatečně reprezentativní už jen svou postavou, oba tedy měli správné předpoklady stát se novými dojo-cho. Jednoho zářijového týdne jsme se tedy ještě s několika dalšími aikidisty z žižkovského dojo vypravili uspořádat exhibiční ukázku aikido, která měla být zároveň náborem pro širokou veřejnost, tentokrát do oddílu dětí i dospělých. Moc si toho nepamatuji, ale Kuře s námi tradičně mlátilo o zem a rozhazovalo podstatně vyšší a silnější osoby mužského pohlaví do všech stran. Potom ovšem nastalo to trudné období počátků, které se nevyhne žádnému nově vzniklému dojo. Občas jsem se zastavil, ale byly to návštěvy spíše sporadické než pravidelné, což musím spravedlivě přiznat. Zrcadlový sál a klavír byl sice raritou, ale počty dospělých na jednotlivých hodinách byly v počátcích velmi skromné, což mohou dosvědčit dokumentární fotografie.</p>
      <p>Hned v počátcích zasáhla štastná náhoda, protože jedním z prvních stálých žáků až do současnosti je pan Petr Karlach, který má nezpochybnitelné zásluhy na propagaci proseckého dojo. Získávat nové členy jsme se snažili různými způsoby - spolupracovníci, jejich příbuzní atd. Začal se rodit duch dojo, neopakovatelný rys každé aikidistické komunity. Vstřícnost, ochota pomáhat druhým, věnovat se začátečníkům, nezištnost při výuce se přenáší od učitelů k žákům a také naopak. Na tomto místě je třeba určitě připomenout Ivu, naši spořádanou dívku, která patří právě do této kategorie lidí a jako další z pamětníků má nezastupitelnou roli na utváření ducha dojo a v proseckém dojo, podobně jako Taťulda, cvičí od samého počátku. Další dobrou duší proseckého dojo s neutuchající snahou všem pomáhat je paní Málková, náš nejstarší člen a zřejmě nejstarší členka České asociace aikido. Pravidelně se stará o žaludky našich dvou senseiů a také výzdoba dojo by bez její pomoci a nápadů nebyla tak příjemná.</p>

      <h3>Školní rok 2003/2004</h3>
      <p>V roce 2003 už začala být situace poněkud stabilizovanější v počtu účastníků a v červenci se letní školy v Českých Budějovicích zúčastnila již slušná skupina proseckých aikidistů připomeňme Tescovi, Petra s Pavlínou, Katku a Ivu a samozřejmě trojici dětí od Jindrů, kteří nám ovšem díky stěhování na druhý konec Prahy bohužel na počátku roku 2004 zřejmě definitivně mizí. Září roku 2003 vzbudilo velké naděje, protože začátečníků s novým školním rokem 2003/2004 dorazila spousta a někteří krátce po vyzkoušení zdejší nálady na dojo aikidu propadli natolik, že dokonce byli ochotni vyrazit na víkendovou stáž do Českých Budějovic i jinam po vlastech českých. Tady jsem poprvé začal poznávat Lachtana, Mrkviče a Vencu, Pečkina s Kukinem, kteří na tréninky musí dojíždět do Prahy a přece je to neodradí.</p>
      <p>Rok 2003 také přinesl první technické stupně složené na tradičních zkouškových stážích na Balkáně, kterých se účastnilo čím dál více aikidistů z Proseka. Z nediferencované masy nových členů v roce 2004, z nichž bohužel přes veškeré naše usilí během pár týdnů či měsíců mnozí odejdou, se začali vynořovat osobnosti jako Lucka-Zuzka, Hanka, Drobek, Bejbina. Začínáme cvičit tři dny v týdnu a někteří nadšenci díky laskavosti balkánského dojo-cho docházejí i na čtvrtý trénink v týdnu na Žižkov. Vznikají klubová trička a tak se některých akcí můžeme zúčastňovat jako bratři a sestry v triku, počtem ovšem značně převyšujeme původní trnkovské trio, a pochopitelně budíme závist ostatních dojo. Účast na společných nikoliv pouze aikidistických akcích brzo každému přidělí nějakou specifickou přezdívku a obvykle svědčí o poměrně silném začlenění do struktury dojo a také upevňuje naše vzájemné vztahy. To se ovšem již dostávám do doby téměř současné. Výčet společných akcí by díky nasazení Kuřete se Smejkim byl opravdu dlouhý, zmíním proto pouze snahu učinit z některých z nás suchozemců a blátošlapů vodáky, což se daří s úspěchy střídavými, vždy ovšem se zážitky hlubokými.</p>
    
      <h3>Školní rok 2004/2005</h3>
      <p>Z části začátečníků se za poslední 2-3 roky stali zkušení zkouškoví matadoři a pozvolna se začíná vytvářet skupina pokročilých, na jejichž bedrech nyní především leží odpovědnost starat se o nově příchozí začátečníky, protože je již naštěstí dávnou minulostí situace soukromých tréninků, kdy počet držitelů hakamy (učitelů) převyšoval počet začátečníků. Tradiční zakončení roku formou tisíce seků (misogi) se v roce 2004 poprvé uskutečnilo také na Proseku.</p>
      <p>První stáž proběhla již v květnu 2004 a také se na Proseku zastavil poprvé zahraniční učitel pan Marco Jaccoud ze Švýcarska.</p>
      <p>Za mnohé z těchto nápadů a aktivit jsme vděčni žižkovskému dojo a po stránce technické a didaktické našim učitelům, zejména pánům Kodymovi, Vetterovi a Ikedovi. Málem bych zapomněl na další jedinečnou událost, rodina Tescofilů se na počátku roku 2004 rozrostla o malého Kubíka, který již v září stejného roku poprvé vyzkoušel kimono a tradiční vítání občánků prožil v obleku typicky japonském, prosecké dojo se tedy pyšní nejen nejstarší cvičenkou aikida v rámci České asociace aikida.</p>
      <p>Také učitelé prodělávají vývoj a tak slečna Legnerová je již držitelkou druhého danu a bezpochyby důvodem, proč mnohé z žen si troufnou aikido nejdříve vyzkoušet a občas také začít věnovat této aktivitě většinu svého volného času. Pan Smejkal zase v průběhu učení dětí i dospělých sám dospěl k prvnímu danu a fyzickou kondici svou i nás ostatních podstatně utužil. Vše se mění a vše plyne, běh času nás omílá, z paměti mnohé zážitky mizí a snad jen fotografie občas vyvolají z tmavých hlubin zapomnění tváře dříve tak známé, či veselé historky, které se původně zdály být nezapomenutelné. Za sebe si pouze přeji, aby tlaku času odolala, z mého pohledu věc nejpodstatnější, atmosféra plná vzájemného přátelství, kterou si při každé vzpomínce na události s proseckým dojo spojené mimoděk vybavím.</p>

      <h3>Kapitolka o dětech</h3>
      <p>Výuka dětí v aikidu je velmi specifická a vyžaduje od učitelů poněkud odlišný přístup, než je při hodinách dospělých. V tomto ohledu je třeba ocenit Smejkiho, který hned na prvním tréninku děti uchvátí a vedení DDM je potom překvapeno, kolik zájemců se na kroužek aikida hlásí. Osobně jsem často překvapen nasazením některých dětí a jejich touhou se stále zlepšovat, zde se mi vybaví postavička droboučké Katky nebo malého Davida a také pochopitelně trojlístku od Jindrů. Obrovským úspěchem je skutečnost, že se podařilo překonat tradiční častou obměnu dětí v kroužku a část dětí chodí nejenom od září 2002 až do současnosti, ale Láďa, Matouš, Jirka a David se stali již rovnocennými členy oddílu dospělých a účastí na stážích se jim podařilo složit i zkoušky na technické stupně dospělých. Pravidelná spolupráce s dalšími dětskými oddíly v rámci ČAA a účast na dětských stážích umožnila v roce 2004 první vedení samostatné dětské stáže slečně Legnerové v Třebíči, kde má dětský oddíly již dlouholetou tradici. V průběhu let 2002-2005 se dětský oddíl podílel také na různých exhibičních akcích pořádaných DDM, které byly většinou úspěšné nejenom z hlediska náboru nových členů, ale také reprezentace DDM na Proseku. Snad je tedy i vedení DDM na Proseku s naší činností spokojeno a bude i v budoucnu našim plánům vycházet vstříc.</p>
      
      <h3>Školní rok 2005/2006</h3>
      <p>Počátek školního roku byl ve znamení rekonstrukce původních prostor, kde se nacházelo dojo, a s nimiž jsme nebyli moc spokojeni, hlavně z hlediska prostoru na cvičení a sociálního příslušenství. Září a říjen jsme z důvodu rekonstrukce trávili v pronajatých prostorech školy v Čakovicích a bylo to skutečně náročné, zejména pro osoby pracující. Jediný, kdo si cvičení v Čakovicích pochvaloval, byla Bejbina, protože cesta z tréninku domů se jí podstatně zkrátila. Účast na cvičeních byla ponejvíce studentská a většina účasníku byla o 14 a více let mladší než já, což je na jednu stranu pro mne tristní, ale na druhou stranu to dokazuje, že aikido lze skutečně cvičit v jakémkoliv věku a že se lze včlenit i do aikidistického kolektivu, který je v převážné míře o generaci mladší než vy.</p>
      <p>Dne 30.10.2005 nastal ten slavný den, kdy nám byl otevřen nový aikidistický stánek v DDM na Proseku. Někteří se tak těšili a byli tak zvědaví, že přišli jen stěhovat (ano i takové obětavé jedince máme ve svých řadách, ještě jednou díky Miloši a Petře). Rychle jsme naložili tatami v Čakovicích a s nedočkavostí poprvé vstoupili do zrekonstruované budovy a byla to skutečně paráda, prostor na cvičení světlý a podstatně větší, šatny a WC nové a krásně čisté a hlavně sprchy, náš letitý sen, abychom už nemuseli hrát hru na prase. První trénink vedl Smejki, protože má největší zásluhy a nejvíce času trávil jednáním s vedením DDM. Od listopadu už tedy fungujeme a dokonce čtyřikrát v týdnu. Trochu se nám sice oslabil příliv nových členů díky stěhování, změnám časů a dnů tréninků, z důvodu cvičení v Čakovicích, ale snad se to zlepší a zase přijdou lidé, kteří časem získají třeba i svou vlastní přezdívku a obohatí naši sbírku obličejů na společných fotografiích z různých akcí.</p>
      <p>V průběhu listopadu a počátkem prosince 2005 dolaďujeme vybavení dojo, zkoušíme nový rám na utěsnění tatami a novou výzdobu. Také v tomto období přichází období zkoušek, na které se tradičně pilně připravujeme, abychom nedělali ostudu. Ostudu jsme snad neudělali a tak se část členů proseckého dojo zase posunula o stupínek dál. Začínají převažovat držitelé 4. a vyššího kjú, takže se dá řící, že jsme již oddílem pokročilým s tradicí sice krátkou, ale naší.</p>
      <p>Autor - Jizva</p>

      <h3>Školní rok 2006/2007</h3>
      <p>V lednu byla již tradičně dětská stáž v Praze na Balkáně, kde nechyběly děti z Proseka. V březnu jsme zorganizovali regionální stáž na PROSEKU, kterou vedla Eliška Šilková z Přerova, byla to 1. regionální stáž, kterou vedla žena. V dubnu měl stáž pan R. Chmocker v Chomutově. Pozvali jsme pana Schmockera i k nám na prosecké dojo a ten pozvání přijal. O prázdninách nechyběla naše účast v Mnichově Hradišti a na Letní škole v Českých Budějovicích. Smejki zde dělal zkoušky na 2. Dan. Na podzim jsme podnikli spoustu akcí typů: divadlo, voda, kola, dovolená v Itálii apod. V zimě bylo již tradiční pečení u Roupečáků. Na proseckém dojo v průběhu roku přibili noví členové (Horolezec, Číňan, Doktor, Čenda atd.), kteří posílili naše řady a stmelili kolektiv.</p>
      <p>Autor - Kuře</p>

      <h3>Školní rok 2007/2008</h3>
      <p>Tento rok nezačal úplně nejšťastněji. Smejki byl v průběhu ledna hospitalizován na Bulovce kvůli plicím, takže tréninky mělo převážně Kuře a to skoro do konce prázdnin. Naštěstí ji sem tam vypomáhali Dračice, Strejda, Venca a další, kterým patří velké díky.</p>
      <p>V lednu byla dětská stáž na Balkáně. V březnu se konaly tradičně „Pády na sněhu“ na Zadově. V dubnu nás vzal Strejda na střelnici, abychom si nemysleli, že aikido je rychlejší než kulka. Na Proseku jsme měli hned dvě zahraniční návštěvy, a to Marco a R. Schmockera. Moc pěkně jsme si zacvičili. V květnu byla v Praze na Balkáně stáž pana Bernarda Caloze, jak jinak než skvělá. V červnu jsme si sjeli vodu Ohři. Tentokrát jsme s sebou měli Číňana a tak o živou muziku přímo na vodě nebyla nouze.</p>
      <p>V červnu také byla stáž Mirka Kodyma v Praze, kde od nás dělali zkoušky: Blonďák (6. kyu), Kuba, Horolezec a Číňan (5. kyu). V červenci Mnichovo Hradiště (Kuře, Dračice, Doktor, Venca, Horolezec, Jirka Český) a pak hned Letní škola v Českých Budějovicích (Kuře, Smejki, Venca, Dračice, Doktor, Číňanové, Taťulda, Kryštof, Štépa, Jirka Culka). Tady dělali zkoušky na 1. kyu Dračice a Venca. Myslím, že byli moc dobří :-). Přesně 1.8. se stala velmi smutná příhoda – náš kamarád MATOUŠ KRAITL se utopil. Byl to moc hodný kluk a bude nám chybět ...</p>
      <p>Autor - Kuře</p>
    </div>
  </div>
);

  export default Historie;